import { StyleSheet } from 'react-native';

export const globalStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        paddingBottom: 20,
    },
    header: {
        fontSize: 24,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 20,
        color: '#333',
    },
    input: {
        borderWidth: 1,
        borderColor: '#aeaeae',
        width: '90%',
        marginVertical: 10,
        height: 50,
        padding: 10,
        borderRadius: 5,
    },
    submitButton: {
        width: '50%',
        backgroundColor: '#000',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
        borderRadius: 10,
        marginBottom: 20,
    },
    submitButtonText: {
        color: 'white',
        fontSize: 18,
        textTransform: 'uppercase',
        fontWeight: 'bold',
    },
    filterContainer: {
        flexDirection: 'row',
        width: '90%',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    filterTab: {
        width: '30%',
        backgroundColor: '#ffffff',
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: 'black',
    },
    activeFilterTab: {
        width: '30%',
        backgroundColor: 'black',
        borderColor: 'black',
    },
    filterTabText: {
        color: 'black',
        fontSize: 15,
        fontWeight: 'bold',
    },
    activeFilterTabText: {
        color: 'white',
        fontSize: 15,
    },
    todoItem: {
        padding: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
        backgroundColor: '#f9f9f9',
        borderRadius: 5,
        marginBottom: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 1,
        elevation: 2,
    },
    todoTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
    },
    todoDescription: {
        fontSize: 14,
        color: '#666',
        marginTop: 5,
    },
    doneTodo: {
        textDecorationLine: 'line-through',
    },
    noTodosText: {
        textAlign: 'center',
        marginTop: 50,
        fontSize: 16,
        color: '#999',
    },
    dividerLine: {
        height: 1,
        width: '90%',
        backgroundColor: '#aeaeae',
        marginVertical: 15,
    },
    todosContainer: {
        marginTop: 10,
    },
});